/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangCycloramaRouteImport } from './routes/$lang/cyclorama'
import { Route as LangGalerieRouteImport } from './routes/$lang/galerie'
import { Route as LangGalleryRouteImport } from './routes/$lang/gallery'
import { Route as LangLegalRouteImport } from './routes/$lang/legal'
import { Route as LangPostProductionRouteImport } from './routes/$lang/post-production'
import { Route as LangBookIndexRouteImport } from './routes/$lang/book/index'
import { Route as LangBookConfirmationRouteImport } from './routes/$lang/book/confirmation'
import { Route as LangBookContactRouteImport } from './routes/$lang/book/contact'
import { Route as LangBookManualRouteImport } from './routes/$lang/book/manual'
import { Route as LangDiscoveryIndexRouteImport } from './routes/$lang/discovery/index'
import { Route as LangDiscoverySlugRouteImport } from './routes/$lang/discovery/$slug'
import { Route as LangPlateauSlugRouteImport } from './routes/$lang/plateau/$slug'
import { Route as LangReserverIndexRouteImport } from './routes/$lang/reserver/index'
import { Route as LangReserverConfirmationRouteImport } from './routes/$lang/reserver/confirmation'
import { Route as LangReserverContactRouteImport } from './routes/$lang/reserver/contact'
import { Route as LangReserverManuelRouteImport } from './routes/$lang/reserver/manuel'
import { Route as LangBookConfiguratorIndexRouteImport } from './routes/$lang/book/configurator/index'
import { Route as LangBookConfiguratorDatesRouteImport } from './routes/$lang/book/configurator/dates'
import { Route as LangBookConfiguratorDetailsRouteImport } from './routes/$lang/book/configurator/details'
import { Route as LangBookConfiguratorStageRouteImport } from './routes/$lang/book/configurator/stage'
import { Route as LangBookConfiguratorTeamRouteImport } from './routes/$lang/book/configurator/team'
import { Route as LangReserverConfigurateurIndexRouteImport } from './routes/$lang/reserver/configurateur/index'
import { Route as LangReserverConfigurateurCoordonneesRouteImport } from './routes/$lang/reserver/configurateur/coordonnees'
import { Route as LangReserverConfigurateurDatesRouteImport } from './routes/$lang/reserver/configurateur/dates'
import { Route as LangReserverConfigurateurEquipeRouteImport } from './routes/$lang/reserver/configurateur/equipe'
import { Route as LangReserverConfigurateurPlateauRouteImport } from './routes/$lang/reserver/configurateur/plateau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCycloramaRoute = LangCycloramaRouteImport.update({
  id: '/cyclorama',
  path: '/cyclorama',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangGalerieRoute = LangGalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangGalleryRoute = LangGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLegalRoute = LangLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPostProductionRoute = LangPostProductionRouteImport.update({
  id: '/post-production',
  path: '/post-production',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookIndexRoute = LangBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookConfirmationRoute = LangBookConfirmationRouteImport.update({
  id: '/book/confirmation',
  path: '/book/confirmation',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookContactRoute = LangBookContactRouteImport.update({
  id: '/book/contact',
  path: '/book/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookManualRoute = LangBookManualRouteImport.update({
  id: '/book/manual',
  path: '/book/manual',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDiscoveryIndexRoute = LangDiscoveryIndexRouteImport.update({
  id: '/discovery/',
  path: '/discovery/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDiscoverySlugRoute = LangDiscoverySlugRouteImport.update({
  id: '/discovery/$slug',
  path: '/discovery/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPlateauSlugRoute = LangPlateauSlugRouteImport.update({
  id: '/plateau/$slug',
  path: '/plateau/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangReserverIndexRoute = LangReserverIndexRouteImport.update({
  id: '/reserver/',
  path: '/reserver/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangReserverConfirmationRoute =
  LangReserverConfirmationRouteImport.update({
    id: '/reserver/confirmation',
    path: '/reserver/confirmation',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangReserverContactRoute = LangReserverContactRouteImport.update({
  id: '/reserver/contact',
  path: '/reserver/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangReserverManuelRoute = LangReserverManuelRouteImport.update({
  id: '/reserver/manuel',
  path: '/reserver/manuel',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookConfiguratorIndexRoute =
  LangBookConfiguratorIndexRouteImport.update({
    id: '/book/configurator/',
    path: '/book/configurator/',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangBookConfiguratorDatesRoute =
  LangBookConfiguratorDatesRouteImport.update({
    id: '/book/configurator/dates',
    path: '/book/configurator/dates',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangBookConfiguratorDetailsRoute =
  LangBookConfiguratorDetailsRouteImport.update({
    id: '/book/configurator/details',
    path: '/book/configurator/details',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangBookConfiguratorStageRoute =
  LangBookConfiguratorStageRouteImport.update({
    id: '/book/configurator/stage',
    path: '/book/configurator/stage',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangBookConfiguratorTeamRoute =
  LangBookConfiguratorTeamRouteImport.update({
    id: '/book/configurator/team',
    path: '/book/configurator/team',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangReserverConfigurateurIndexRoute =
  LangReserverConfigurateurIndexRouteImport.update({
    id: '/reserver/configurateur/',
    path: '/reserver/configurateur/',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangReserverConfigurateurCoordonneesRoute =
  LangReserverConfigurateurCoordonneesRouteImport.update({
    id: '/reserver/configurateur/coordonnees',
    path: '/reserver/configurateur/coordonnees',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangReserverConfigurateurDatesRoute =
  LangReserverConfigurateurDatesRouteImport.update({
    id: '/reserver/configurateur/dates',
    path: '/reserver/configurateur/dates',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangReserverConfigurateurEquipeRoute =
  LangReserverConfigurateurEquipeRouteImport.update({
    id: '/reserver/configurateur/equipe',
    path: '/reserver/configurateur/equipe',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangReserverConfigurateurPlateauRoute =
  LangReserverConfigurateurPlateauRouteImport.update({
    id: '/reserver/configurateur/plateau',
    path: '/reserver/configurateur/plateau',
    getParentRoute: () => LangRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cyclorama': typeof LangCycloramaRoute
  '/$lang/galerie': typeof LangGalerieRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/post-production': typeof LangPostProductionRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/book/confirmation': typeof LangBookConfirmationRoute
  '/$lang/book/contact': typeof LangBookContactRoute
  '/$lang/book/manual': typeof LangBookManualRoute
  '/$lang/discovery/$slug': typeof LangDiscoverySlugRoute
  '/$lang/plateau/$slug': typeof LangPlateauSlugRoute
  '/$lang/reserver/confirmation': typeof LangReserverConfirmationRoute
  '/$lang/reserver/contact': typeof LangReserverContactRoute
  '/$lang/reserver/manuel': typeof LangReserverManuelRoute
  '/$lang/book/': typeof LangBookIndexRoute
  '/$lang/discovery/': typeof LangDiscoveryIndexRoute
  '/$lang/reserver/': typeof LangReserverIndexRoute
  '/$lang/book/configurator/dates': typeof LangBookConfiguratorDatesRoute
  '/$lang/book/configurator/details': typeof LangBookConfiguratorDetailsRoute
  '/$lang/book/configurator/stage': typeof LangBookConfiguratorStageRoute
  '/$lang/book/configurator/team': typeof LangBookConfiguratorTeamRoute
  '/$lang/reserver/configurateur/coordonnees': typeof LangReserverConfigurateurCoordonneesRoute
  '/$lang/reserver/configurateur/dates': typeof LangReserverConfigurateurDatesRoute
  '/$lang/reserver/configurateur/equipe': typeof LangReserverConfigurateurEquipeRoute
  '/$lang/reserver/configurateur/plateau': typeof LangReserverConfigurateurPlateauRoute
  '/$lang/book/configurator/': typeof LangBookConfiguratorIndexRoute
  '/$lang/reserver/configurateur/': typeof LangReserverConfigurateurIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cyclorama': typeof LangCycloramaRoute
  '/$lang/galerie': typeof LangGalerieRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/post-production': typeof LangPostProductionRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/book/confirmation': typeof LangBookConfirmationRoute
  '/$lang/book/contact': typeof LangBookContactRoute
  '/$lang/book/manual': typeof LangBookManualRoute
  '/$lang/discovery/$slug': typeof LangDiscoverySlugRoute
  '/$lang/plateau/$slug': typeof LangPlateauSlugRoute
  '/$lang/reserver/confirmation': typeof LangReserverConfirmationRoute
  '/$lang/reserver/contact': typeof LangReserverContactRoute
  '/$lang/reserver/manuel': typeof LangReserverManuelRoute
  '/$lang/book': typeof LangBookIndexRoute
  '/$lang/discovery': typeof LangDiscoveryIndexRoute
  '/$lang/reserver': typeof LangReserverIndexRoute
  '/$lang/book/configurator/dates': typeof LangBookConfiguratorDatesRoute
  '/$lang/book/configurator/details': typeof LangBookConfiguratorDetailsRoute
  '/$lang/book/configurator/stage': typeof LangBookConfiguratorStageRoute
  '/$lang/book/configurator/team': typeof LangBookConfiguratorTeamRoute
  '/$lang/reserver/configurateur/coordonnees': typeof LangReserverConfigurateurCoordonneesRoute
  '/$lang/reserver/configurateur/dates': typeof LangReserverConfigurateurDatesRoute
  '/$lang/reserver/configurateur/equipe': typeof LangReserverConfigurateurEquipeRoute
  '/$lang/reserver/configurateur/plateau': typeof LangReserverConfigurateurPlateauRoute
  '/$lang/book/configurator': typeof LangBookConfiguratorIndexRoute
  '/$lang/reserver/configurateur': typeof LangReserverConfigurateurIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cyclorama': typeof LangCycloramaRoute
  '/$lang/galerie': typeof LangGalerieRoute
  '/$lang/gallery': typeof LangGalleryRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/post-production': typeof LangPostProductionRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/book/confirmation': typeof LangBookConfirmationRoute
  '/$lang/book/contact': typeof LangBookContactRoute
  '/$lang/book/manual': typeof LangBookManualRoute
  '/$lang/discovery/$slug': typeof LangDiscoverySlugRoute
  '/$lang/plateau/$slug': typeof LangPlateauSlugRoute
  '/$lang/reserver/confirmation': typeof LangReserverConfirmationRoute
  '/$lang/reserver/contact': typeof LangReserverContactRoute
  '/$lang/reserver/manuel': typeof LangReserverManuelRoute
  '/$lang/book/': typeof LangBookIndexRoute
  '/$lang/discovery/': typeof LangDiscoveryIndexRoute
  '/$lang/reserver/': typeof LangReserverIndexRoute
  '/$lang/book/configurator/dates': typeof LangBookConfiguratorDatesRoute
  '/$lang/book/configurator/details': typeof LangBookConfiguratorDetailsRoute
  '/$lang/book/configurator/stage': typeof LangBookConfiguratorStageRoute
  '/$lang/book/configurator/team': typeof LangBookConfiguratorTeamRoute
  '/$lang/reserver/configurateur/coordonnees': typeof LangReserverConfigurateurCoordonneesRoute
  '/$lang/reserver/configurateur/dates': typeof LangReserverConfigurateurDatesRoute
  '/$lang/reserver/configurateur/equipe': typeof LangReserverConfigurateurEquipeRoute
  '/$lang/reserver/configurateur/plateau': typeof LangReserverConfigurateurPlateauRoute
  '/$lang/book/configurator/': typeof LangBookConfiguratorIndexRoute
  '/$lang/reserver/configurateur/': typeof LangReserverConfigurateurIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/contact'
    | '/$lang/cyclorama'
    | '/$lang/galerie'
    | '/$lang/gallery'
    | '/$lang/legal'
    | '/$lang/post-production'
    | '/$lang/'
    | '/$lang/book/confirmation'
    | '/$lang/book/contact'
    | '/$lang/book/manual'
    | '/$lang/discovery/$slug'
    | '/$lang/plateau/$slug'
    | '/$lang/reserver/confirmation'
    | '/$lang/reserver/contact'
    | '/$lang/reserver/manuel'
    | '/$lang/book/'
    | '/$lang/discovery/'
    | '/$lang/reserver/'
    | '/$lang/book/configurator/dates'
    | '/$lang/book/configurator/details'
    | '/$lang/book/configurator/stage'
    | '/$lang/book/configurator/team'
    | '/$lang/reserver/configurateur/coordonnees'
    | '/$lang/reserver/configurateur/dates'
    | '/$lang/reserver/configurateur/equipe'
    | '/$lang/reserver/configurateur/plateau'
    | '/$lang/book/configurator/'
    | '/$lang/reserver/configurateur/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/contact'
    | '/$lang/cyclorama'
    | '/$lang/galerie'
    | '/$lang/gallery'
    | '/$lang/legal'
    | '/$lang/post-production'
    | '/$lang'
    | '/$lang/book/confirmation'
    | '/$lang/book/contact'
    | '/$lang/book/manual'
    | '/$lang/discovery/$slug'
    | '/$lang/plateau/$slug'
    | '/$lang/reserver/confirmation'
    | '/$lang/reserver/contact'
    | '/$lang/reserver/manuel'
    | '/$lang/book'
    | '/$lang/discovery'
    | '/$lang/reserver'
    | '/$lang/book/configurator/dates'
    | '/$lang/book/configurator/details'
    | '/$lang/book/configurator/stage'
    | '/$lang/book/configurator/team'
    | '/$lang/reserver/configurateur/coordonnees'
    | '/$lang/reserver/configurateur/dates'
    | '/$lang/reserver/configurateur/equipe'
    | '/$lang/reserver/configurateur/plateau'
    | '/$lang/book/configurator'
    | '/$lang/reserver/configurateur'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/contact'
    | '/$lang/cyclorama'
    | '/$lang/galerie'
    | '/$lang/gallery'
    | '/$lang/legal'
    | '/$lang/post-production'
    | '/$lang/'
    | '/$lang/book/confirmation'
    | '/$lang/book/contact'
    | '/$lang/book/manual'
    | '/$lang/discovery/$slug'
    | '/$lang/plateau/$slug'
    | '/$lang/reserver/confirmation'
    | '/$lang/reserver/contact'
    | '/$lang/reserver/manuel'
    | '/$lang/book/'
    | '/$lang/discovery/'
    | '/$lang/reserver/'
    | '/$lang/book/configurator/dates'
    | '/$lang/book/configurator/details'
    | '/$lang/book/configurator/stage'
    | '/$lang/book/configurator/team'
    | '/$lang/reserver/configurateur/coordonnees'
    | '/$lang/reserver/configurateur/dates'
    | '/$lang/reserver/configurateur/equipe'
    | '/$lang/reserver/configurateur/plateau'
    | '/$lang/book/configurator/'
    | '/$lang/reserver/configurateur/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/cyclorama': {
      id: '/$lang/cyclorama'
      path: '/cyclorama'
      fullPath: '/$lang/cyclorama'
      preLoaderRoute: typeof LangCycloramaRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/galerie': {
      id: '/$lang/galerie'
      path: '/galerie'
      fullPath: '/$lang/galerie'
      preLoaderRoute: typeof LangGalerieRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/gallery': {
      id: '/$lang/gallery'
      path: '/gallery'
      fullPath: '/$lang/gallery'
      preLoaderRoute: typeof LangGalleryRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/legal': {
      id: '/$lang/legal'
      path: '/legal'
      fullPath: '/$lang/legal'
      preLoaderRoute: typeof LangLegalRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/post-production': {
      id: '/$lang/post-production'
      path: '/post-production'
      fullPath: '/$lang/post-production'
      preLoaderRoute: typeof LangPostProductionRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/': {
      id: '/$lang/book/'
      path: '/book'
      fullPath: '/$lang/book/'
      preLoaderRoute: typeof LangBookIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/confirmation': {
      id: '/$lang/book/confirmation'
      path: '/book/confirmation'
      fullPath: '/$lang/book/confirmation'
      preLoaderRoute: typeof LangBookConfirmationRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/contact': {
      id: '/$lang/book/contact'
      path: '/book/contact'
      fullPath: '/$lang/book/contact'
      preLoaderRoute: typeof LangBookContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/manual': {
      id: '/$lang/book/manual'
      path: '/book/manual'
      fullPath: '/$lang/book/manual'
      preLoaderRoute: typeof LangBookManualRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/discovery/': {
      id: '/$lang/discovery/'
      path: '/discovery'
      fullPath: '/$lang/discovery/'
      preLoaderRoute: typeof LangDiscoveryIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/discovery/$slug': {
      id: '/$lang/discovery/$slug'
      path: '/discovery/$slug'
      fullPath: '/$lang/discovery/$slug'
      preLoaderRoute: typeof LangDiscoverySlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/plateau/$slug': {
      id: '/$lang/plateau/$slug'
      path: '/plateau/$slug'
      fullPath: '/$lang/plateau/$slug'
      preLoaderRoute: typeof LangPlateauSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/': {
      id: '/$lang/reserver/'
      path: '/reserver'
      fullPath: '/$lang/reserver/'
      preLoaderRoute: typeof LangReserverIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/confirmation': {
      id: '/$lang/reserver/confirmation'
      path: '/reserver/confirmation'
      fullPath: '/$lang/reserver/confirmation'
      preLoaderRoute: typeof LangReserverConfirmationRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/contact': {
      id: '/$lang/reserver/contact'
      path: '/reserver/contact'
      fullPath: '/$lang/reserver/contact'
      preLoaderRoute: typeof LangReserverContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/manuel': {
      id: '/$lang/reserver/manuel'
      path: '/reserver/manuel'
      fullPath: '/$lang/reserver/manuel'
      preLoaderRoute: typeof LangReserverManuelRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/configurator/': {
      id: '/$lang/book/configurator/'
      path: '/book/configurator'
      fullPath: '/$lang/book/configurator/'
      preLoaderRoute: typeof LangBookConfiguratorIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/configurator/dates': {
      id: '/$lang/book/configurator/dates'
      path: '/book/configurator/dates'
      fullPath: '/$lang/book/configurator/dates'
      preLoaderRoute: typeof LangBookConfiguratorDatesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/configurator/details': {
      id: '/$lang/book/configurator/details'
      path: '/book/configurator/details'
      fullPath: '/$lang/book/configurator/details'
      preLoaderRoute: typeof LangBookConfiguratorDetailsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/configurator/stage': {
      id: '/$lang/book/configurator/stage'
      path: '/book/configurator/stage'
      fullPath: '/$lang/book/configurator/stage'
      preLoaderRoute: typeof LangBookConfiguratorStageRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book/configurator/team': {
      id: '/$lang/book/configurator/team'
      path: '/book/configurator/team'
      fullPath: '/$lang/book/configurator/team'
      preLoaderRoute: typeof LangBookConfiguratorTeamRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/configurateur/': {
      id: '/$lang/reserver/configurateur/'
      path: '/reserver/configurateur'
      fullPath: '/$lang/reserver/configurateur/'
      preLoaderRoute: typeof LangReserverConfigurateurIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/configurateur/coordonnees': {
      id: '/$lang/reserver/configurateur/coordonnees'
      path: '/reserver/configurateur/coordonnees'
      fullPath: '/$lang/reserver/configurateur/coordonnees'
      preLoaderRoute: typeof LangReserverConfigurateurCoordonneesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/configurateur/dates': {
      id: '/$lang/reserver/configurateur/dates'
      path: '/reserver/configurateur/dates'
      fullPath: '/$lang/reserver/configurateur/dates'
      preLoaderRoute: typeof LangReserverConfigurateurDatesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/configurateur/equipe': {
      id: '/$lang/reserver/configurateur/equipe'
      path: '/reserver/configurateur/equipe'
      fullPath: '/$lang/reserver/configurateur/equipe'
      preLoaderRoute: typeof LangReserverConfigurateurEquipeRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reserver/configurateur/plateau': {
      id: '/$lang/reserver/configurateur/plateau'
      path: '/reserver/configurateur/plateau'
      fullPath: '/$lang/reserver/configurateur/plateau'
      preLoaderRoute: typeof LangReserverConfigurateurPlateauRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangContactRoute: typeof LangContactRoute
  LangCycloramaRoute: typeof LangCycloramaRoute
  LangGalerieRoute: typeof LangGalerieRoute
  LangGalleryRoute: typeof LangGalleryRoute
  LangLegalRoute: typeof LangLegalRoute
  LangPostProductionRoute: typeof LangPostProductionRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBookConfirmationRoute: typeof LangBookConfirmationRoute
  LangBookContactRoute: typeof LangBookContactRoute
  LangBookManualRoute: typeof LangBookManualRoute
  LangDiscoverySlugRoute: typeof LangDiscoverySlugRoute
  LangPlateauSlugRoute: typeof LangPlateauSlugRoute
  LangReserverConfirmationRoute: typeof LangReserverConfirmationRoute
  LangReserverContactRoute: typeof LangReserverContactRoute
  LangReserverManuelRoute: typeof LangReserverManuelRoute
  LangBookIndexRoute: typeof LangBookIndexRoute
  LangDiscoveryIndexRoute: typeof LangDiscoveryIndexRoute
  LangReserverIndexRoute: typeof LangReserverIndexRoute
  LangBookConfiguratorDatesRoute: typeof LangBookConfiguratorDatesRoute
  LangBookConfiguratorDetailsRoute: typeof LangBookConfiguratorDetailsRoute
  LangBookConfiguratorStageRoute: typeof LangBookConfiguratorStageRoute
  LangBookConfiguratorTeamRoute: typeof LangBookConfiguratorTeamRoute
  LangReserverConfigurateurCoordonneesRoute: typeof LangReserverConfigurateurCoordonneesRoute
  LangReserverConfigurateurDatesRoute: typeof LangReserverConfigurateurDatesRoute
  LangReserverConfigurateurEquipeRoute: typeof LangReserverConfigurateurEquipeRoute
  LangReserverConfigurateurPlateauRoute: typeof LangReserverConfigurateurPlateauRoute
  LangBookConfiguratorIndexRoute: typeof LangBookConfiguratorIndexRoute
  LangReserverConfigurateurIndexRoute: typeof LangReserverConfigurateurIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangContactRoute: LangContactRoute,
  LangCycloramaRoute: LangCycloramaRoute,
  LangGalerieRoute: LangGalerieRoute,
  LangGalleryRoute: LangGalleryRoute,
  LangLegalRoute: LangLegalRoute,
  LangPostProductionRoute: LangPostProductionRoute,
  LangIndexRoute: LangIndexRoute,
  LangBookConfirmationRoute: LangBookConfirmationRoute,
  LangBookContactRoute: LangBookContactRoute,
  LangBookManualRoute: LangBookManualRoute,
  LangDiscoverySlugRoute: LangDiscoverySlugRoute,
  LangPlateauSlugRoute: LangPlateauSlugRoute,
  LangReserverConfirmationRoute: LangReserverConfirmationRoute,
  LangReserverContactRoute: LangReserverContactRoute,
  LangReserverManuelRoute: LangReserverManuelRoute,
  LangBookIndexRoute: LangBookIndexRoute,
  LangDiscoveryIndexRoute: LangDiscoveryIndexRoute,
  LangReserverIndexRoute: LangReserverIndexRoute,
  LangBookConfiguratorDatesRoute: LangBookConfiguratorDatesRoute,
  LangBookConfiguratorDetailsRoute: LangBookConfiguratorDetailsRoute,
  LangBookConfiguratorStageRoute: LangBookConfiguratorStageRoute,
  LangBookConfiguratorTeamRoute: LangBookConfiguratorTeamRoute,
  LangReserverConfigurateurCoordonneesRoute:
    LangReserverConfigurateurCoordonneesRoute,
  LangReserverConfigurateurDatesRoute: LangReserverConfigurateurDatesRoute,
  LangReserverConfigurateurEquipeRoute: LangReserverConfigurateurEquipeRoute,
  LangReserverConfigurateurPlateauRoute: LangReserverConfigurateurPlateauRoute,
  LangBookConfiguratorIndexRoute: LangBookConfiguratorIndexRoute,
  LangReserverConfigurateurIndexRoute: LangReserverConfigurateurIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
